// Auto-generated build version information
// This file is generated by scripts/generate-version.sh during build
// DO NOT EDIT MANUALLY

export interface VersionInfo {
  version: string
  buildDate: string
  gitHash: string
}

declare const versionInfo: VersionInfo
export default versionInfo
